---
title: "R Notebook"
output: html_notebook
---

ok - so assuming we have the first notebook run and have created the pcs variable - let's aggregate centers for each variety

```{r}
pcs2 <- subset(pcs, Category  %in% c("Red", "White"))
#pcs2 <- pcs2[pcs2$points>82,]

samplesize = 250 # don't take wines with fewer than 200 reviews
pcs2 <- pcs2 %>% group_by(Variety, Category) %>% filter(n() >= samplesize) %>% ungroup() %>% as.data.frame()
pc_wineload <- aggregate(pcs2[1:150], by= list(pcs2$Variety, pcs2$Category), FUN = mean)
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 == "Chardonnay" & pc_wineload$Group.2 == "Red"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 == "Sauvignon Blanc" & pc_wineload$Group.2 == "Red"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 == "Aglianico" & pc_wineload$Group.2 == "White"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 == "Pinot Noir" & pc_wineload$Group.2 == "White"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 == "Syrah" & pc_wineload$Group.2 == "White"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 ==  "Viognier" & pc_wineload$Group.2 == "Red"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 ==  "Red Blend"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 ==  "White Blend"),]
pc_wineload <- pc_wineload[!(pc_wineload$Group.1 ==  "Malbec" & pc_wineload$Group.2 == "White"),]

rownames(pc_wineload) <- 1:nrow(pc_wineload)

head(pc_wineload,20)

```

ok - now lets subtract each element from the cluster center of each other element

```{r}

wine_distances<- pcs[,c(1:2,265:276)]
colnames(wine_distances)<-c("PC1","PC2","Farm","Year","Name (Region)","Points","Price","Review","Rating","Review Date","Alc %","Variety","Category","Reviewer")

for (ii in 1:nrow(pc_wineload)){
  wine_distances[pc_wineload$Group.1[ii]] <-100
  for (jj in 1:nrow(pcs)){
  wine_distances[jj,pc_wineload$Group.1[ii]]<-(sum(abs(pcs[jj,1:5]-pc_wineload[ii,3:7]))) # cityblock distance
  }
}

head(wine_distances)
```

OK so now we have distances, let's try to sort by them -- find the 5 wines closest or furthest away from Cab Savs, for instance

```{r}
N=5

library(ggplot2)

sub_wine_distances <- wine_distances
sub_wine_distances$price <- as.numeric(gsub('[$,]','',as.character(sub_wine_distances$Price)))

sub_wine_distances <- subset(sub_wine_distances, Variety %in% "Chardonnay")
sub_wine_distances <- subset(sub_wine_distances, Price < 300)

ndx <- order(sub_wine_distances$'Malbec', decreasing = F)[1:N]

ggplot(data=pc_wineload[1:30])+geom_point(aes(x = PC1, y = PC2, colour = Group.2))+geom_point(data=sub_wine_distances[ndx,], aes(x = PC1, y = PC2, colour = 'Selected Wines'))

head(sub_wine_distances[ndx,c(3,5,4,7,11,12)])


```